### ISSUE TITLE
What the f you mean "Skiddies" ?

### ISSUE THREAD

**Issue by Zhodisov** [culturally/Insta-OSINT#1]
"# Unfortunately i'm implementing junk code and simple protection against script kiddies so the API will not get abused"

Why are you saying this? This API is public everyone can use it since the implementation of Instagram API v1.

like toutatis

**Comment by culturally** [comment]
> "# Unfortunately i'm implementing junk code and simple protection against script kiddies so the API will not get abused"
> 
> 
> 
> Why are you saying this? This API is public everyone can use it since the implementation of Instagram API v1.
> 
> 
> 
> 
> 
> 
> 
> like toutatis

Well first of all watch your language and second of all i obtained the API from Instagram iOS version 103 which i personally bypassed pinning. Even tho the API may be public i still wouldn't appreciate if some kids would spam it and Instagram would have to change it as they like to do so. Also simple junk code won't hurt you will it?

**Comment by Zhodisov** [comment]
Yes, that makes sense, sorry for the inconvenience
