### ISSUE TITLE
This don't work anymore?

### ISSUE THREAD

**Issue by Idkwhome69** [culturally/Insta-OSINT#6]
The program keeps crashing after entering the username.Pleaae help

**Comment by culturally** [comment]
can you provide some error log or something? the program should still work.

**Comment by Idkwhome69** [comment]
There's no error the program opens and allows me to insert the username but when i press enter after inserting the username the program closes automatically and nothing happens

**Comment by culturally** [comment]
I assume you are just double clicking on the python file which is the weong way of running. Open cmd -> cd into directory with the files -> pip install requirements.txt -> python or python3 main.py 

then tell me the output

**Comment by Idkwhome69** [comment]
Yup tried that.. It's not fetching the email and phone number  though :(

**Comment by culturally** [comment]
There are many issues why this could happen: Your ip is being rate limited/being count as malicious or the account does not have email/phone linked. Keep in mind it won't give you full email or phone number. I either inputting email of the account as target instead of username or trying other account or ip. (also it doesn't work for celebrity accounts for obvious reasons)

**Comment by Idkwhome69** [comment]
I tried it for my own account and it has email and phone number linked to it..Will using an vpn help?

**Comment by culturally** [comment]
Maybe yes maybe no who knows it is very individual maybe they changed the api but i doubt it i can try it later.

**Comment by Idkwhome69** [comment]
Thankyou so much.. Please test it and update it if needed I really need this tool🙏🏻

**Comment by culturally** [comment]
Works perfectly fine issue closed

**Comment by Idkwhome69** [comment]
Thankyou so much its working now just one thing you should've mentioned that when you try this on someone elses account it sends them an email that someone tried to reset your password XD
